<?php
echo "\n"; 
echo "<!doctype html>\n"; 
echo "<html lang=\"en-us\">\n"; 
echo "  <head>\n"; 
echo "    <meta charset=\"utf-8\">\n"; 
echo "    <title>Realtime Chat Widget using Pusher</title>\n"; 
echo "    \n"; 
echo "    <link rel=\"stylesheet/less\" type=\"text/css\" href=\"lib/twitter-bootstrap/lib/bootstrap.less\">\n"; 
echo "    <script src=\"lib/less/less-1.1.5.min.js\"></script>\n"; 
echo "    \n"; 
echo "    <link href=\"styles.css\" rel=\"stylesheet\" />\n"; 
echo "    <link href=\"pusher-chat-widget.css\" rel=\"stylesheet\" />\n"; 
echo "    \n"; 
echo "    <!--[if lt IE 9]>\n"; 
echo "    <script src=\"//html5shiv.googlecode.com/svn/trunk/html5.js\"></script>\n"; 
echo "    <![endif]-->\n"; 
echo "    <script src=\"http://code.jquery.com/jquery-1.7.1.min.js\"></script>\n"; 
echo "    <script src=\"http://js.pusher.com/1.12/pusher.min.js\"></script>\n"; 
echo "    <script src=\"js/PusherChatWidget.js\"></script>    \n"; 
echo "    <script>\n"; 
echo "      $(function() {     \n"; 
echo "        var pusher = new Pusher('49e26cb8e9dde3dfc009')\n"; 
echo "        var chatWidget = new PusherChatWidget(pusher, {\n"; 
echo "          appendTo: '#pusher_chat_widget'\n"; 
echo "        });\n"; 
echo "      });\n"; 
echo "    </script>\n"; 
echo "  </head>\n"; 
echo "  <body>\n"; 
echo "\n"; 
echo "    <div class=\"container\">\n"; 
echo "\n"; 
echo "      <div class=\"topbar\">\n"; 
echo "        <div class=\"fill\">\n"; 
echo "          <div class=\"container\">\n"; 
echo "            <a class=\"brand\" href=\"/\">Realtime Chat Widget using Pusher</a>\n"; 
echo "          </div>\n"; 
echo "        </div>\n"; 
echo "      </div>\n"; 
echo "\n"; 
echo "      <div class=\"hero-unit\">\n"; 
echo "        <h1>Realtime Chat Widget</h1>\n"; 
echo "        <p>This page demonstrates a Realtime Chat widget built using <a href=\"http://pusher.com\">Pusher</a>. This functionality can easily be added to any PHP application.</p>\n"; 
echo "        <p>The widget can easily be added to any page and the channel name for the chat is generated based on the URL of the page. The chat message events are triggered via PHP using the <a href=\"https://github.com/squeeks/Pusher-PHP\">PHP Pusher library</a>.</p>\n"; 
echo "        <p><a href=\"https://github.com/pusher/pusher-realtime-chat-widget\" class=\"btn primary large\" target=\"_blank\">Get the code &raquo;</a></p>\n"; 
echo "        <p><small>We plan to update this sample to contain backend code in other technologies. Feel free to <a href=\"https://github.com/pusher/pusher-realtime-chat-widget\">fork</a> and try it for yourself.</small></p>\n"; 
echo "      </div>\n"; 
echo "      \n"; 
echo "      <section class=\"realtime-chat\">\n"; 
echo "        \n"; 
echo "        <div class=\"page-header\">\n"; 
echo "          <h1>Realtime Chat Widget Example</h1>\n"; 
echo "        </div>\n"; 
echo "        \n"; 
echo "        <div class=\"row\">\n"; 
echo "          \n"; 
echo "          <div class=\"span5\">\n"; 
echo "            <p>\n"; 
echo "              <p><strong>Why don't you provide your email address</strong> so your Gravatar can be looked up and used in the Chat Widget</p>\n"; 
echo "            </p>\n"; 
echo "          </div>\n"; 
echo "          <div class=\"span5\" id='pusher_chat_widget'>\n"; 
echo "          </div>\n"; 
echo "          \n"; 
echo "        </div>\n"; 
echo "        \n"; 
echo "      </section>\n"; 
echo "\n"; 
echo "      <footer>\n"; 
echo "        <p></p>\n"; 
echo "      </footer>\n"; 
echo "\n"; 
echo "    </div> <!-- /container -->\n"; 
echo "\n"; 
echo "    <a href=\"https://github.com/pusher/pusher-realtime-chat-widget\"><img style=\"position: absolute; top: 0; right: 0; border: 0; z-index: 10000;\" src=\"https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png\" alt=\"Fork me on GitHub\"></a>\n"; 
echo "\n"; 
echo "  </body>\n"; 
echo "</html>\n";
?>